apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      env: green
  template:
    metadata:
      labels:
        app: myapp
        env: green
    spec:
      containers:
      - name: myapp
        image: europe-west1.-docker.pkg.dev/k8s-537022-project/my-app-images/my-app:test
        ports:
        - containerPort: 80
